### ISSUE TITLE
Showing error with "!pip install git+https://github.com/phiyodr/building-inspection-toolkit"

### ISSUE THREAD

**Issue by mir-abir-hossain** [phiyodr/building-inspection-toolkit#11] opened 2023-09-18 18:20 UTC
`!pip install git+https://github.com/phiyodr/building-inspection-toolkit` is giving me this error:

Collecting git+https://github.com/phiyodr/building-inspection-toolkit
  Cloning https://github.com/phiyodr/building-inspection-toolkit to /tmp/pip-req-build-b6h333cq
  Running command git clone --filter=blob:none --quiet https://github.com/phiyodr/building-inspection-toolkit /tmp/pip-req-build-b6h333cq
  Resolved https://github.com/phiyodr/building-inspection-toolkit to commit 948472321ff63ebca28a4e3724698ba2c99f44f1
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in building-inspection-toolkit setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          numpy > 1.20requeststorchtorchvisionpandasPillowpatoolpathlibtqdmmatplotlibopencv-python-headlessefficientnet_pytorchtorchmetrics
                ~~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


I don't know what to do.

**Comment by phiyodr** [comment] 2023-09-18 19:01
Hi, I cannot reproduce your error. But in [setup.py](https://github.com/phiyodr/building-inspection-toolkit/blob/431b6484ceb8deecb561241f2dc72d10487a7226/setup.py#L28) there were indeed commas missing – as your error message implies. Is it working now?

**Comment by phiyodr** [comment] 2023-09-20 12:22
I close the issue. If the problem remains, please open it again.

**Closed as completed by phiyodr** 2023-09-20 12:22 UTC
